Amar weather-app w3
HackYourHomework/React-class33 pull request #17
Opened 2021-11-16 22:52 UTC by Amar-Mahdy

2021-11-18 20:28 UTC, crevulus commented
Hi Amar,

This is a vast improvement from week 1! It seems like you're really getting to grips with React very quickly. I've left a lot of compliments in my review and I'm very impressed.

As for things that are missing, the main one is tests! I know the requirements to have "every component tested" is no longer a requirement, but I don't see any tests at all. Please include some basic tests for a few of your components and/or some of your logic, functions etc.

And there's also some things you've left in there since week one that should have already been changed. Look out for them in my review.

2021-11-18 20:29 UTC, crevulus requested changes

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/WeatherList.js
> +                <Card key={index} city={city} handleDelete={handleDelete} />
good, you caught the "key" error from last time. Just FYI, it is best **not** to use `index` for a key, but instead to use a unique identifier from the data. 🟢

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/package.json
> +    "uuid": "^8.3.2",
I see lots of packages here that you're not using. `uuid`, `whatwg-fetch`, `bootstrap`. Be sure to remove them from your `package.json` and `uninstall` via `npm`. 🟢

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/forecast.js
> +        <strong>min temp: </strong> {getCelcius(city.main.temp_min)}
You might want to check this method: your app currently says London is max temp **-260.0**! I know it's cold there but not that cold 🔴

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/card.js
> +      <Header city={city} />
Good component-isation here

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/MainForecast.js
> +      <h4>
I mentioned this in my last review. Please correct it! https://github.com/HackYourHomework/React-class33/pull/8#discussion_r744119866 🔴

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/MainForecast.js
> +        <strong>{city.description}</strong>
I mentioned this, too, but left it open: https://github.com/HackYourHomework/React-class33/pull/8#discussion_r744119918
The problem here is that the description should have a capital letter. The data you receive is all lower-case letters, so you need to find a way to convert the first letter to upper case. It's a small difference, but it's very important that your websites match client expectations! 🔴

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/forecast.js
> +      </span>{" "}
What is this empty space for? 🟢

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/form.js
> +          placeholder="e.g Groningen"
Good UX

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/form.js
> +          onChange={handleCity}
your `handleCity` function in the parent just sets a global state variable (context api) -- do you really need to write it in the parent and pass it down here? Wouldn't it be better to set it here directly, where it's used? 🔴

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/cityPage.js
> +import { useNavigate } from "react-router-dom";
if you have two imports from the same module, put them in the same import statement.🟠

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/cityPage.js
> +import { useNavigate } from "react-router-dom";
I haven't even used react router v6 yet - very cool!

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/cityPage.js
> +        console.log(err);
Could you communicate these errors to the user somehow? 🟠

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/cityPage.js
> +          <button className="back" onClick={() => navigate("/")}>
`useNavigate` has a specific method for going back - that's basically why it was added to react-router v6! Better to use that: https://dev.to/salehmubashar/usenavigate-tutorial-react-js-aop 🟢

2021-11-18 20:29 UTC, crevulus commented on project/hackyourweather/src/components/cityPage.js
> +          <ResponsiveContainer width={1300} height={500}>
This is some advanced stuff!

2021-11-18 20:34 UTC, Amar-Mahdy commented on project/hackyourweather/src/converter/converter.js
> +export const getCelcius = (kelvin) => {
thanks you so much for your nice impression, i appreciate it very well.
and yes utils is a descriptive name

2021-11-18 20:35 UTC, Amar-Mahdy commented on project/hackyourweather/src/App.css
> +  width: 30%;
not actually, but i probably need to do it more responsive

2021-11-18 20:36 UTC, Amar-Mahdy commented on project/hackyourweather/src/components/WeatherContext.js
> +  const [isLoading, setIsLoading] = useState(false);
maybe to false ?

2021-11-18 20:37 UTC, Amar-Mahdy commented on project/hackyourweather/src/components/form.js
> +          onChange={handleCity}
that,s crazy, your right, why do i need it out there

2021-11-18 20:39 UTC, Amar-Mahdy commented on project/hackyourweather/src/components/cityPage.js
> +import { useNavigate } from "react-router-dom";
what do you mean by the first comment?

2021-11-19 10:14 UTC, Amar-Mahdy commented on project/hackyourweather/src/components/WeatherContext.js
> +  const [isLoading, setIsLoading] = useState(false);
yes i forgot it

2021-11-19 16:42 UTC, crevulus commented on project/hackyourweather/src/components/WeatherContext.js
> +      value={[
This is not the correct way to structure the `value` prop. It should be an object, i.e. `value={{ // values in here }}`. Wihtout this, you cannot use object destructuring when you try to access context values. https://www.freecodecamp.org/news/array-and-object-destructuring-in-javascript/ 🔴

2021-11-19 16:46 UTC, crevulus commented on project/hackyourweather/src/components/WeatherContext.js
> +      value={[
you will have to change the way you destructure on line 8 in `WeatherList`, too.

2021-11-19 18:16 UTC, crevulus requested changes
What a beautiful website! There's some very advanced stuff in there, and you've paid close attention to creating beautiful visuals. Well done!

Your code is a bit messy in places. You're passing state across components rather than using your Context provider as your single source of truth, you've got some functions that do essentially the same thing, and your renaming things is unnecessary. That's causing errors in your UI that are hard to track.

There's also one key thing missing: tests! The requirement for tests is definitely smaller, but that doesn't mean 0 tests. Please include some tests with your next commit.

2021-11-19 18:27 UTC, Amar-Mahdy commented
updating the reviews

2021-11-19 18:35 UTC, closed without merging